/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package expert.system.lab;

import java.io.File;
import java.io.IOException;

// Посмотреть 98 страницу, 101, 129, 132, 135, 137
// Цель процесса поиска - показать, что начальная вершина разрешима
// Заключительная вершина разрешима
public class App {

    private static final String DIRECT_EXAMLES = System.getProperty("user.dir") + File.separator + "examples" + File.separator;

    public static void main(String[] args) throws IOException {
        Graph graph = ParserRules.parse(DIRECT_EXAMLES + "example_5");
        graph.outputGraph("build_graph1");
        Graph newGraph = graph.bruteForceMethod();
        graph.outputGraph("build_graph2");
        newGraph.outputGraph("build_graph3");
    }
}
